Feat/#9: 노션 API 를 활용한 건의사항 post api 구현
GDSC-PKNU-21-22/pknu-notice-back pull request #15
Opened 2023-05-14 12:53 UTC by hwinkr

## 🤠 개요

* Closes : #9 
* 노션 api 를 사용해서 건의사항 post 를 위한 api 를 구현했어요

## 💫 설명

* `express.Router()` 를 사용해서 `apis/suggestion` 내부에 api 로직을 분리했어요
* index.ts
  * 서버로 넘어오는 데이터를 json 형식으로 변경하기 위해서 `express.json()` 을 추가했어요.
 

## 📷 스크린샷 (Optional)

https://github.com/hwinkr/algorithm/assets/68489467/b1ad89ee-811b-4be6-8dfc-1e1eb0890acc

2023-05-20 02:37 UTC, pp449 requested changes
노션 API 사용하는거 고생많았겠군요 !

2023-05-20 02:37 UTC, pp449 commented on src/apis/suggestion/service.ts
> +dotenv.config();
일일이 dotenv를 이용해서 가져오는것 보다 src/config 에 설정을 모아두고 사용하는게 더 좋을거 같아요

2023-05-20 02:37 UTC, pp449 commented on src/index.ts
> +app.use(express.json());
찾아보니까 최근 Node 버전부터 이 코드는 자동으로 실행된다 하더라고요
있어도 상관없을거 같아요 !

2023-05-21 05:40 UTC, hwinkr commented on src/apis/suggestion/service.ts
> +dotenv.config();
저도 그게 좋을 것 같아요~ 옮기도록 하겠습니다

2023-05-21 05:41 UTC, hwinkr commented
수정 완료 했습니다~

2023-05-21 11:25 UTC, pp449 requested changes
제가 하나 더 있는거 못봤었군요,,

2023-05-21 11:25 UTC, pp449 commented on src/apis/suggestion/service.ts
> +    parent: { database_id: process.env.NOTION_DATABASE_ID },
엇 여기도 process 로 되어있어서 여기만 바꾸면 될거 같아요~

2023-05-22 05:57 UTC, hwinkr commented
수정 했어여~

2023-05-22 06:28 UTC, pp449 approved these changes
👍 죠습니다~

2023-05-22 06:28 UTC, pp449 approved these changes
👍 죠습니다~

2023-05-22 06:31 UTC, merged