Feat: 건물 정보 api 라우팅 추가
GDSC-PKNU-21-22/pknu-notice-back pull request #180
Opened 2024-01-27 10:12 UTC by hwinkr

## 🤠 개요

- closes : #179 
- 지도 페이지에서 사용하는 건물 정보를 얻기 위한 api를 구현했어요

## 💫 설명

- 클라이언트 측에서 바로 학교 서버에 요청을 하니, CORS 에러가 발생해서 서버 측에서 학교 서버에 요청을 한 후 클라이언트 측에서 렌더링하기 쉽도록 데이터를 포맷팅한 후 넘겨주는 방식으로 구현했어요

## 📷 스크린샷 (Optional)

2024-01-29 16:14 UTC, pp449 requested changes

2024-01-29 16:14 UTC, pp449 commented on src/apis/building-info/service.ts
> +  };
헤더 값을 이렇게 설정하는 이유가 있나요??

2024-01-29 16:14 UTC, pp449 commented on src/apis/building-info/controllers.ts
> +});
요청이 올때마다 크롤링을 한 결과값을 반환하는데 해당 데이터는 자주 변경되지 않기때문에 DB로 저장하는게 좋지 않을까요?

2024-02-02 00:14 UTC, hwinkr commented on src/apis/building-info/service.ts
> +  };
헤더값을 이렇게 설정하지 않으면 학교 측 서버에 request를 보낼 때 자꾸 404에러가 발생 했어서, 브라우저의 network탭에서 확인할 수 있는 http request와 동일한 헤더 값을 설정하니 해결 됐어서 이렇게 설정했어요~

2024-02-02 00:20 UTC, hwinkr commented on src/apis/building-info/controllers.ts
> +});
노드 서버가 학교 측 서버에 대신 http request를 보내서 받은 데이터를 다시 노드 -> 클라이언트 순으로 전달해주는 것이기 때문에 크롤링은 아닌 것 같아요. 자주 변경 되지 않는 데이터인것은 맞지만 학교 측 서버를 빌리는 개념이라서 디비에 저장해야 한다는 생각은 안했는데 디비에 저장했을 경우 장점이 뭘까요?

2024-02-02 04:10 UTC, pp449 commented on src/apis/building-info/controllers.ts
> +});
크롤링이 아니었네요.. ㅎㅎ
저는 이중 요청으로 네트워크 통신이 많아지는거 같고 너무 학교 서버에 의존하는거 같아 디비에 저장하는게 좋다고 생각했어요

아직 문제가 발생한건 아니니 나중에 문제가 있으면 수정하는것도 좋을거 같아요 👍

2024-02-02 04:11 UTC, pp449 approved these changes
✅ LGTM

2024-02-02 04:37 UTC, merged